### ISSUE TITLE
Thoughts on helpernode, to provide shared/bootstrap services?

### ISSUE THREAD

**Issue by victorhooi** [cgruver/okd4-upi-lab-setup#11]
I'm still new - so forgive me if this is a naive question.

But what are your thoughts on [helpernode](https://github.com/RedHatOfficial/ocp4-helpernode)

Video stream discussing it here - https://youtu.be/wZYx4_xBSUQ

Could this be used in this lab setup, or help provide some of the shared services (LB, DNS, HTTP, DHCP/PXE etc.)

![hn](https://user-images.githubusercontent.com/243499/86521961-74ada700-be9a-11ea-8c8c-26f049cc733b.png)

**Comment by cgruver** [comment]
Yes, I believe that you could use the helper node concept to run this.

In my home lab, the DNS, DHCP,PXE, and HTTP servers are also serving up resources for non OKD machines.  I am emulating the operations of a larger data-center.  My bastion host also provides the core infrastructure for the whole lab.

I also take you through setting up the individual infrastructure pieces for educational reasons.  I am a HUGE fan of developers and operations engineers gaining a broader appreciation for how the underlying infrastructure actually works.

So, while I don't give explicit tutorials on PXE, DNS, DHCP, etc... you at least get some exposure to the installation and configuration.

If you are just deploying an OKD cluster and nothing more, then there is no reason that you could not use the helper node.  It will automate a lot of what I show you how to install and set up.

Cheers!

**Comment by disposab1e** [comment]
@victorhooi I agree with @cgruver .. his lab and docs are brilliant if you want to learn the details about what you need for an successful OKD UPI installation. And it's highly flexible! I have learned a lot from him!

If you want a simpler approach to install OKD you might have a look [here](https://github.com/disposab1e/okd-lab)... I have done this with the help of this lab and @cgruver . Not as flexible but perhaps simpler to get started.

**Comment by cgruver** [comment]
Closing this now.
