### ISSUE TITLE
Manual KVM Host Install specifies CentOS 7

### ISSUE THREAD

**Issue by bdlink** [cgruver/okd4-upi-lab-setup#13]
Shouldn't https://github.com/cgruver/okd4-upi-lab-setup/blob/master/docs/pages/KVM_Host_Install.md be changed to use centos 8? or explain why CentOS 7 is used here on the host nodes whereas CentOS 8 is used for the bastion.

**Comment by cgruver** [comment]
@bdlink You are correct...  That's an error in the Doc.

I'm in the process of moving the whole thing to CentOS Streams.
