### ISSUE TITLE
Move workloads to masters

### ISSUE THREAD

**Issue by ghost** [cgruver/okd4-upi-lab-setup#14]
Hi,

My current setup is 3 master and 3 worker nodes. Thus, following this https://github.com/cgruver/okd4-upi-lab-setup/blob/master/docs/pages/InfraNodes.md#designate-master-nodes-as-infrastructure-nodes it’s very nice that you can move ingress pods to masters(infra) without making them scheduleEnabled. However, I am wondering what would be the right way of moving workloads (image-registry, monitoring, logging) to master nodes the same way keeping masters without worker role. Following that https://github.com/cgruver/okd4-upi-lab-setup/blob/master/docs/pages/InfraNodes.md#move-workloads-to-the-new-infra-nodes monitoring and image registry are stuck at pending state due to master=“” role.

Thank you

**Comment by cgruver** [comment]
@Born2Bake The rest of those instructions were written for non-master infra node.

I will post updated instructions for the master nodes.  In the mean time, try this:

* IngressController: `oc patch -n openshift-ingress-operator ingresscontroller default --patch '{"spec":{"nodePlacement":{"nodeSelector":{"matchLabels":{"node-role.kubernetes.io/infra":""}},"tolerations":[{"key":"infra","value":"infraNode","effect":"NoSchedule"},{"key":"infra","value":"infraNode","effect":"NoExecute"},,{"key":"node-role.kubernetes.io/master","effect":"NoSchedule"}]}}}' --type=merge`

* ImageRegistry: `oc patch configs.imageregistry.operator.openshift.io cluster --patch '{"spec":{"nodeSelector":{"node-role.kubernetes.io/infra":""},"tolerations":[{"key":"infra","value":"infraNode","effect":"NoSchedule"},{"key":"infra","value":"infraNode","effect":"NoExecute"},,{"key":"node-role.kubernetes.io/master","effect":"NoSchedule"}]}}' --type=merge`

Add the following to each section of your cluster-monitoring-config.yaml

```yaml
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
```

**Comment by cgruver** [comment]
I made a change to the docs.  See if that works for you.

**Comment by ghost** [comment]
> I made a change to the docs. See if that works for you.

Thank you.

I think moving image-registry is dangerous if its already attached to pvc - https://prnt.sc/woin25 hehe

**Comment by ghost** [comment]
> > I made a change to the docs. See if that works for you.
> 
> Thank you.
> 
> I think moving image-registry is dangerous if its already attached to pvc - https://prnt.sc/woin25 hehe

ah that issue is different: rook-ceph is not running on master nodes so it cant attach pvc when image registry is sent to the master;

P.S. I ve changed monitoring configmap, and it did not help so all monitoring pods are still running on worker nodes.

**Comment by ghost** [comment]
> > > I made a change to the docs. See if that works for you.
> > 
> > 
> > Thank you.
> > I think moving image-registry is dangerous if its already attached to pvc - https://prnt.sc/woin25 hehe
> 
> ah that issue is different: rook-ceph is not running on master nodes so it cant attach pvc when image registry is sent to the master;
> 
> P.S. I ve changed monitoring configmap, and it did not help so all monitoring pods are still running on worker nodes.

Line 13 typo -        - key: "node-role.kubernetes.io/master"

Issue can be closed, thank you very much for help.

**Comment by cgruver** [comment]
> > I made a change to the docs. See if that works for you.
> 
> Thank you.
> 
> I think moving image-registry is dangerous if its already attached to pvc - https://prnt.sc/woin25 hehe

Yes.  That is very true.  If it's already got content.
