### ISSUE TITLE
Consider using RHEL instead of CentOS Stream

### ISSUE THREAD

**Issue by bdlink** [cgruver/okd4-upi-lab-setup#15]
Just a suggestion.  
Now that RH is making 16 copies of RHEL available for production use, based on a RH developer account (Feb 1, we'll see if it happens), RHEL becomes a candidate.
It really depends on your focus.  If the focus is on the OKD part, then a stable OS for the services and underlying virtualization on the is helpful.  As CentOS used to be downstream of RHEL, it fit the bill.  Now CentOS stream is the incubator for RHEL and can be expected to be (much?) less stable.  This is reasonable if you are checking out the changes to RHEL, but not an advantage if you are using it as a platform for something else. RHEL 8.3 and CentOS 8 are both on kernel 4.18 so the newest stuff that does not require kernel 5 should be there.
I am looking at moving from CentOS 8 to RHEL 8.3 where I need stability, and look at Fedora for what may be coming up (or for running on top of FCOS)

**Comment by cgruver** [comment]
That's not a bad idea...  But, I will probably stick with CentOS Stream for now.

1. It's embarrassing, but I actually have more than 16 servers in my lab...  ;-)
2. I like providing a tutorial that doesn't require folks to sign up for anything.  Even though, a Red Hat developer account is very useful.
3. CentOS Stream should be pretty stable.  Time will tell, but it's really just the next RHEL patches before they go to subscribers.

**Comment by bdlink** [comment]
"Should" is such a hopeful word.  I hope you are right.  
I do not recall how many parts of your automation would need to be changed to go CentOS -> RHEL or CentOS -> CentOS Stream.  If it is minor configuration then it either could be an option? Or perhaps an option to have preconfigured the OS on the hosts and just automate the virualization on top of it.
I noticed that a RHEL installation wants a licensing (or developer account) confirmation step, which CentOS does not require.
