### ISSUE TITLE
Bare-metal LoadBalancer service

### ISSUE THREAD

**Issue by ghost** [cgruver/okd4-upi-lab-setup#16]
Hello,

I am wondering, what can be used in order to expose non-http traffic/tcp traffic? Thus, for bare-metal solution the most popular solution is MetalLB. However, it's a known fact that using L2 arp mode is not very good choice. So I am interested in what solution you guys use in your bare-metal clusters? Is it https://github.com/redhat-cop/keepalived-operator ? Is it MetalLB with BGP? If it's MetalLB with BGP, could you please advise what's the correct way of configuring it because I am currently stuck with it:

- I have deployed metallb in the cluster. 
- Created pfsense vm with frr installed. 
- Configured AS and neighbours (3 master and 3 worker nodes of the cluster). 
- Added configmap, and then created nginx + lb service.

So then I can see 172.16.1.160/32 ip is advertised for nginx - https://prnt.sc/xfzfkx Problem is that I can curl it from (3) master and (3) worker nodes but if I go outside of the cluster within the same LAN 172.16.1.0/24, it cant be curl'd so I cant access it from other vms. Any advice on that one please?

**Comment by cgruver** [comment]
Hey, you can get a lot more help than I am able to provide if you join the OpenShift-users channel in Kubernetes Slack.

There's a lot of us that hang out there and help people.

https://kubernetes.slack.com/archives/C6AD6JM17

**Comment by cgruver** [comment]
I just use HA Proxy in my lab.
