### ISSUE TITLE
DeployKvmHost.sh incorrect for current CentOS 8.3

### ISSUE THREAD

**Issue by bdlink** [cgruver/okd4-upi-lab-setup#18]
As, for instance, referring to the repo Minimal which no longer exists.  I would guess the kickstart may need to be changed as well.

The manual install for KVM hosts should be fine, but the pxe boot was a nice feature.

**Comment by cgruver** [comment]
Yes, I need to update everything for CentOS Streams...

I'm on a customer engagement which is not allowing much time for my lab work...  I need to update several things.
