### ISSUE TITLE
Error mirroring to nexus

### ISSUE THREAD

**Issue by bdlink** [cgruver/okd4-upi-lab-setup#19]
Still working through existing pages, with CentOS8.3.

Install yaml file uses OpenshiftSDN, changed to default network type to have a better chance with 4.6

oc from 4.5 could not pull down latest oc_client and oc_install so switched to current 4.6. one which seemed to work.

mirrorOkdRelease.sh failed to mirror to nexus with error (have replaced domain with XXX):
error: unable to connect to nexus.XXX:5001/origin: Get "https://nexus.XXX:5001/v2/": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0

Defining GODEBUG in script doesn't help.  I guess in earlier instructions, need to enter a SAN for the nexus cert.

**Comment by cgruver** [comment]
Thanks Bruce!  

I need to spend a weekend updating this.
