### ISSUE TITLE
Join us in fighting covid as an iPXE expert

### ISSUE THREAD

**Issue by sokoow** [cgruver/okd4-upi-lab-setup#2]
Hey,

Cool project, it ideally looks like you'd be able to help us with fighting COVID with it!

We're planning to use a lot of iPXE related things, and your expertise would be really useful for us.

Join us on: https://devpost.com/software/help-education-sector-to-produce-more-laptops-for-students

Greetings, Karol & the team.

**Comment by cgruver** [comment]
Hey, I'm not completely sure of your architecture, but given that iPXE requires a DHCP server capable of handling PXE clients, have you thought about using something like `kickstart` instead?

Most home routers can't be configured to serve PXE clients.  But a USB key set up with a kickstart file that points it to a known HTTPS address on the internet would work anywhere you can boot and get an IP address with a router.

I haven't used mint, but I think it's a Debian based distro, so kickstart may not work with it.  But there's probably an equivalent for unattended installations.

**Comment by sokoow** [comment]
Yeah, that's more or less what I'm trying to do, so have iPXE on a usb stick as a dropper, then invoke a kernel boot from https with boot params pointing to a preseed, that is also on that https point, and then it should do fine.

**Comment by sokoow** [comment]
exactly like netboot.xyz tried to do things

**Comment by cgruver** [comment]
Interesting!  I've not come across that before.  That's a very interesting project.

**Comment by sokoow** [comment]
https://github.com/sokoow/globalhack-laptop-installer/releases/tag/0.1-alpha-pl
