### ISSUE TITLE
Thx for your help and inspiration!

### ISSUE THREAD

**Issue by disposab1e** [cgruver/okd4-upi-lab-setup#7]
Finally a new [okd-lab](https://github.com/disposab1e/okd-lab)

**Comment by cgruver** [comment]
Excellent!!!

I'm really glad you got it running.  That's fantastic!

This weekend, I'll be updating my lab to OKD 4.5 and FCOS 32.  

I'm also writing a simple Quarkus and Angular application with a Tekton pipeline so folks can deploy a useful app into their lab.

Stay tuned.
