### ISSUE TITLE
Invalid image pruner cron

### ISSUE THREAD

**Issue by jam01** [cgruver/okd4-upi-lab-setup#8]
First, thanks a ton for this guide! It helped me understand a few things here and there.

Here's the issue 
```
E0627 17:27:59.883915      13 controllerimagepruner.go:306] (image pruner) unable to sync: unable to apply objects: failed to update object *v1beta1.CronJob, Namespace=openshift-image-registry, Name=image-pruner: CronJob.batch "image-pruner" is invalid: spec.schedule: Invalid value: "*/0 * * * *": Step of range should be a positive number: */0, requeuing
```

Is the idea that it should run at every hour mark? If so maybe `0 */1 * * *` ?

**Comment by cgruver** [comment]
Interesting, that worked in my last build.   But that is from an older nightly image.  Something may have changed recently to invalidate it.

What OKD version are you running.  I'll try this again and fix it.

**Comment by jam01** [comment]
The oc patch succeeds, but saw that error message on the pods when troubleshooting another issue. I'm on 4.5 nightlies

**Comment by cgruver** [comment]
I'll be updating one of my clusters to 4.5 soon.  I'm still on 4.4

I'll take a look at the pods in my current cluster and see if it's throwing errors.  The image pruner was not well documented when I first set this up.  I don't know if the docs have improved yet.

Thanks for letting me know.  I'll correct it.

**Comment by cgruver** [comment]
Try this... I intended for it to run every day at midnight:  

I think this is what I actually meant to use.  

```
oc patch imagepruners.imageregistry.operator.openshift.io/cluster --type merge -p '{"spec":{"schedule":"0 0 * * *","suspend":false,"keepTagRevisions":3,"keepYoungerThan":60,"resources":{},"affinity":{},"nodeSelector":{},"tolerations":[],"startingDeadlineSeconds":60,"successfulJobsHistoryLimit":3,"failedJobsHistoryLimit":3}}'
```

Docs are here:

https://docs.openshift.com/container-platform/4.4/applications/pruning-objects.html

**Comment by cgruver** [comment]
Fixed it.

Good catch!  I would have been wondering why old images weren't getting cleaned up...  Especially with all the pipeline builds that I have done.

**Comment by jam01** [comment]
Thank you for putting this together. I'm actually using the installer with the oVirt provider, but have used your guide for some things like the pruner or the ingress controller scheduling... but I keep running into issues with the installer so I may give the UPI approach a try
